spring.application.name=material-program

spring.datasource.url=jdbc:postgresql://localhost:5432/material_tracker
spring.datasource.username=MAC
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

